# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='macrocategory',
            name='amount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planning.Amount'),
        ),
    ]
