# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20170814_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='totalVariable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
