# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20170814_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
    ]
