# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrocategory',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
